<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: human.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Human</code>
 */
class Human extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated string name = 1;</code>
     */
    private $name;

    public function __construct() {
        \GPBMetadata\Human::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>repeated string name = 1;</code>
     */
    public function setName(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->name = $arr;
    }

}

