<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: human.proto

namespace GPBMetadata;

class Human
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a2c0a0b68756d616e2e70726f746f22150a0548756d616e120c0a046e61" .
            "6d65180120032809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

