<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a2e0a0c706572736f6e2e70726f746f22160a06506572736f6e120c0a04" .
            "6e616d65180120012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

